set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(
  RVAI_RISCV64_TOOLCHAIN_PREFIX
  "riscv64-linux-gnu"
  CACHE STRING
  "GNU cross-toolchain target prefix"
)

set(CMAKE_C_COMPILER "${RVAI_RISCV64_TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${RVAI_RISCV64_TOOLCHAIN_PREFIX}-g++")

set(CMAKE_FIND_ROOT_PATH "/usr/${RVAI_RISCV64_TOOLCHAIN_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Cross-compilation checks must not attempt to execute RISC-V binaries here.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
